// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf_dqXTxLWDqjefut2fwjoMevz4WBArq0',
    appId: '1:964214171834:web:f1ddd6cdaaf1615a6a7a83',
    messagingSenderId: '964214171834',
    projectId: 'nutrilligent-4ebba',
    authDomain: 'nutrilligent-4ebba.firebaseapp.com',
    storageBucket: 'nutrilligent-4ebba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzeZNHG3P70Z1gGsfBel3MCah6fRerbrg',
    appId: '1:964214171834:android:c4bbc89c76e1e8e66a7a83',
    messagingSenderId: '964214171834',
    projectId: 'nutrilligent-4ebba',
    storageBucket: 'nutrilligent-4ebba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA486Yg0GIRGnb4WiYrdoEooqel9PxtjqQ',
    appId: '1:964214171834:ios:494ba4f4768730e86a7a83',
    messagingSenderId: '964214171834',
    projectId: 'nutrilligent-4ebba',
    storageBucket: 'nutrilligent-4ebba.firebasestorage.app',
    iosBundleId: 'com.example.nutrilligent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA486Yg0GIRGnb4WiYrdoEooqel9PxtjqQ',
    appId: '1:964214171834:ios:494ba4f4768730e86a7a83',
    messagingSenderId: '964214171834',
    projectId: 'nutrilligent-4ebba',
    storageBucket: 'nutrilligent-4ebba.firebasestorage.app',
    iosBundleId: 'com.example.nutrilligent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf_dqXTxLWDqjefut2fwjoMevz4WBArq0',
    appId: '1:964214171834:web:48ff516ab664d1a06a7a83',
    messagingSenderId: '964214171834',
    projectId: 'nutrilligent-4ebba',
    authDomain: 'nutrilligent-4ebba.firebaseapp.com',
    storageBucket: 'nutrilligent-4ebba.firebasestorage.app',
  );

}